### ISSUE TITLE
You have already activated rake 10.4.2, but your Gemfile requires rake 12.0.0

### ISSUE THREAD

**Issue by mailinglists35** [akiko-pusu/redmine_issue_templates#114]
I have redmine redmine-3.3.2-2 installed with bitnami installer (https://bitnami.com/stack/redmine/installer) on centos 7.3 64 bit

I want to install this plugin and I followed the instructions then at step 2 it fails with following output:

```
[root@redmine plugins]# rake redmine:plugins:migrate RAILS_ENV=production
(in /opt/redmine-3.3.2-2/apps/redmine/htdocs)
rake aborted!
Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 12.0.0. Prepending `bundle exec` to your command may solve this.
/opt/redmine-3.3.2-2/apps/redmine/htdocs/config/boot.rb:4:in `<top (required)>'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/config/application.rb:1:in `<top (required)>'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/opt/redmine-3.3.2-2/apps/redmine/htdocs/config/boot.rb:4:in `<top (required)>'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/config/application.rb:1:in `<top (required)>'
/opt/redmine-3.3.2-2/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

I don't know if this is actually an issue with redmine_issue_templates, but I don't know where else to ask.

**Comment by mailinglists35** [comment]
note that I've previously been able to install other plugins (scrum for example)

**Comment by akiko-pusu** [comment]
Hi, @mailinglists35 
Thank you so much for taking an interest in my small plugin.
I wonder if this trouble is due to my plugin, but I'm going to support to solve your problem.

As error message says, please run rake command with "bundle exec" 
> Prepending `bundle exec` to your command may solve this.

Try this:

```
$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```

Maybe not only my plugin but also some other plugin required migration (Create table / Modify table) will be failed if you run "rake redmine:plugins:migrate RAILS_ENV=production" .

Aso please read following BitNami documentation, to install plugin and run migration.
https://docs.bitnami.com/installer/apps/redmine/#how-to-install-a-plugin-on-redmine
(Section: How To Install The Redmine Custom Workflows Plugin?)

If your trouble is not solved after trying bundle exec, could you please let me know the version of my plugin?
You can get plugin version number from plugins/redmine_issue=templates/init.rb.

**Comment by akiko-pusu** [comment]
@mailinglists35 How is your situation?

**Comment by mailinglists35** [comment]
@akiko-pusu thank you for your care; I have been away from that system and will be for another week. will report back as soon as I can get my hands on it again!

**Comment by akiko-pusu** [comment]
Ok, I hope everything works out!
