### ISSUE TITLE
Problems to install the plugin in new redmine 3.3.2

### ISSUE THREAD

**Issue by fofiales** [akiko-pusu/redmine_issue_templates#136]
Hello! First of all, thank you for your plugin!

I have a issue when i try to install this plugin, i dont know if the problem its with my ruby or what, maybe you can help me :)

I have installed the redmine in Ubuntu with bitnami instaler -> bitnami-redmine-3.3.2-2-linux-x64-installer.run
When i put the plugin in the directory with the name "redmine_issue_templates" and execute a migration de results is:

/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/early_time.rb:20: warning: already initialized constant Rake::EARLY
/var/lib/gems/2.4.0/gems/rake-12.0.0/lib/rake/early_time.rb:20: warning: previous definition of EARLY was here
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/late_time.rb:16: warning: already initialized constant Rake::LATE
/var/lib/gems/2.4.0/gems/rake-12.0.0/lib/rake/late_time.rb:16: warning: previous definition of LATE was here
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:3: warning: already initialized constant Rake::Backtrace::SYS_KEYS
/var/lib/gems/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:3: warning: previous definition of SYS_KEYS was here
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:4: warning: already initialized constant Rake::Backtrace::SYS_PATHS
/var/lib/gems/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:4: warning: previous definition of SYS_PATHS was here
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:7: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS
/var/lib/gems/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:7: warning: previous definition of SUPPRESSED_PATHS was here
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:11: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS_RE
/var/lib/gems/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:11: warning: previous definition of SUPPRESSED_PATHS_RE was here
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:15: warning: already initialized constant Rake::Backtrace::SUPPRESS_PATTERN
/var/lib/gems/2.4.0/gems/rake-12.0.0/lib/rake/backtrace.rb:15: warning: previous definition of SUPPRESS_PATTERN was here
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake.rb:69: warning: already initialized constant FileList
/var/lib/gems/2.4.0/gems/rake-12.0.0/lib/rake.rb:69: warning: previous definition of FileList was here
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake.rb:70: warning: already initialized constant RakeFileUtils
/var/lib/gems/2.4.0/gems/rake-12.0.0/lib/rake.rb:70: warning: previous definition of RakeFileUtils was here
yard not installed (gem install yard)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/servicios/redmine-3.3.3-1/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
rake aborted!
SystemStackError: stack level too deep

I have installed gem yard ok (gem install yard), but the problem persist.

Seems that ruby its configurated in two different routes?? Do you know what is my problem and how can i resolve them?

Regards.

**Comment by akiko-pusu** [comment]
Hi, @fofiales
Thank you so much for trying my plugin.
Personally I think  your problem is not due to my plugin. 

For me, it is strange that the version you installed, v3.3.2, and the version displayed above error message, v3.3.1, are different.

Could you please tell me the command you entered in the terminal, to do migration task.
Also please tell me the version of ruby that you use. (E.g. the result of % ruby -v)

Current Redmine is not support ruby 2.4, as following.
http://www.redmine.org/issues/25460

Did you upgrade ruby version after Bitnami Redmine installed?

In addition to this, Bitnami Redmine uses separated ruby and its gems. 
Please confirm the way to install plugin following Bitnami’s documents:
https://docs.bitnami.com/installer/apps/redmine/#how-to-install-a-plugin-on-redmine

**Comment by fofiales** [comment]
Thanks for your quickly answer, im so stupid, i haven´t read the docs.bitnami, the first note is: 

NOTE: Before running the commands shown on this page, you should load the Bitnami stack environment by executing the installdir/use_APPNAME script (Linux and Mac OS X) 

When I have run ./use_redmine  i have been able to install your plugin whitout problems. The problem in my system was that it was getting two different ruby versions, the version of the system default and redmine one.

Thank you for your help.
Regards.

**Comment by akiko-pusu** [comment]
I'm glad to hear that migration completed!
The environmental information you shared is quite helpful for me, because related issues / questions was reported.

Fortunately, Redmine3.4 will be released soon, in a few days. The new version of Bitnami Stack will also be released. I think new version run without problem if you use system-wide ruby such as version 2.4.
