### ISSUE TITLE
Unable to see if there is a new version

### ISSUE THREAD

**Issue by peternijssen** [akiko-pusu/redmine_issue_templates#148]
At the plugin page in Redmine, you can easily check for new versions of plugins.
Somehow Redmine cannot check if there is an update for this plugin, while it can for your other plugin.

![redmine](http://oi68.tinypic.com/23lawif.jpg)

**Comment by akiko-pusu** [comment]
I’ve just fixed. But the plugin’s information url is now change, because registered plugin identified name was required to change...
(Before: https://www.redmine.org/plugins/issue_templates
 After: https://www.redmine.org/plugins/redmine_issue_templates)


This is caused I created this plugin and and registered at Redmine official site before Redmine’s plugin Check Update feature was implemented.
