### ISSUE TITLE
Create issue template but description can NOT support chinese

### ISSUE THREAD

**Issue by tmc9031** [akiko-pusu/redmine_issue_templates#158]
Create issue template, use chinese type in description region and click save
But redmine return "internal error" web page

```
Environment:
  Redmine version                3.4.2
  Ruby version                   2.3.4

redmine_issue_templates v0.1.8
```

**Comment by tmc9031** [comment]
log/production.log

```
Started POST "/global_issue_templates/new" for 127.0.0.1 at 2017-08-14 17:46:26 +0800
Processing by GlobalIssueTemplatesController#new as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"==", "global_issue_template"=>{"title"=>"qwer", "tracker_id"=>"2", "issue_title"=>"qwer", "description"=>"模板管理", "note"=>"", "is_default"=>"0", "enabled"=>"0", "project_ids"=>[""]}, "commit"=>"创建"}
  Current user: Marcus (id=53)
Completed 500 Internal Server Error in 38ms (ActiveRecord: 24.2ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xE6\xA8\xA1\xE6\x9D\xBF...' for column 'description' at row 1: INSERT INTO `global_issue_templates` (`title`, `tracker_id`, `issue_title`, `description`, `note`, `author_id`, `checklist_json`, `created_on`, `updated_on`, `position`) VALUES ('qwer', 2, 'qwer', '模板管理', '', 53, '{}', '2017-08-14 17:46:26', '2017-08-14 17:46:26', 1)):
  plugins/redmine_issue_templates/app/controllers/global_issue_templates_controller.rb:102:in `save_and_flash'
  plugins/redmine_issue_templates/app/controllers/global_issue_templates_controller.rb:37:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by akiko-pusu** [comment]
Hi, @tmc9031 
Thanks for trying my plugin.
I think this is not due to my plugin. It is caused by charset of your mysql server side.

Since “模板” is non-ascii character, that you might fail to insert this string. 

Please try if some ascii (such as English) text can be saved correctly or not.
 If you could save ascii text without any problem,  then, please confirm your database and table’s character set?

E.g. SHOW VARIABLES LIKE 'character\_set\_%’;

Ref. 
[MySQL 5.7 Frequently Asked Questions  /  MySQL 5.7 FAQ: MySQL Chinese, Japanese, and Korean Character Sets
 ](https://dev.mysql.com/doc/refman/5.7/en/faqs-cjk.html)

**Comment by tmc9031** [comment]
@akiko-pusu 
thanks, the problem is that mysql **character_set_database** use latin1, need modify utf8
