### ISSUE TITLE
Custom fields support

### ISSUE THREAD

**Issue by pielat** [akiko-pusu/redmine_issue_templates#175]
Hello,
We found your plugin very useful but some of our trackers have many custom fields (more then 10). Would you be interested in developing your plugin? We can make a normal order and pay for it - it depends on the price :) If you want you can contact me private.
Compatibility: Redmine 3.4.

**Comment by akiko-pusu** [comment]
Hi, I've just merged above PR into my develop branch.
Since this is an experimental feature, please be careful if you hope to try it.
Migration is required and some browsers may not work fine.

Hope this would be any help.
And if you still have interests in this feature, feedback would be highly appreciated!

**Comment by akiko-pusu** [comment]
merged into master branch. please re-open or report new issue!

**Comment by akiko-pusu** [comment]
@pielat 
Hi, I've released v1.0.0 to support custom fields and builtin-fields.
Since this is an experimental feature, please be careful if you hope to try it.

Please see https://github.com/akiko-pusu/redmine_issue_templates/releases/tag/1.0.0
I'm looking forward to your feedback.
