### ISSUE TITLE
Can´t create new model from project -> seTtings -> "task models"

### ISSUE THREAD

**Issue by carodrigues** [akiko-pusu/redmine_issue_templates#186]
Can´t create new model from project -> seTtings -> "task models"
When click on " Include model", an error page is triggered :

Page not found
The page you were trying to access doesn't exist or has been removed.
Back

log: 

Started GET "/redmine/projects/bug/issue_templates/new/bug" for 127.0.0.1 at 2018-06-08 09:33:21 +0100
Processing by IssueTemplatesController#new as HTML
  Parameters: {"project_id"=>"bug", "id"=>"bug"}
  Current user: crodrigues (id=121)
Completed 404 Not Found in 14ms (ActiveRecord: 7.8ms)

ActiveRecord::RecordNotFound (Couldn't find IssueTemplate with 'id'=bug):
  plugins/redmine_issue_templates/app/controllers/issue_templates_controller.rb:48:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

![image](https://user-images.githubusercontent.com/11546961/41147814-48dac0d6-6aff-11e8-8731-e00186aa0ab6.png)

**Comment by akiko-pusu** [comment]
I can’t support you without any environmental information, as I already requested twice at #184 and #185.
Also now I don’t have much time to spare for you.
I wonder you did not run plugin migration task yet. Please read **README** and Redmine’s official site.

**Comment by carodrigues** [comment]
Hi,

Thank you for your time and support.

I reinstalled my system, this is the actual conf:



On this new configuration, the issue #187 doesn´t  happen but i still have
the issue #186.
Yes, i executed the migration task.

Regards,
Carlos

**Comment by akiko-pusu** [comment]
Ok, I just figure out the situation.
And please use another way to create templates and show templates.

1.  Go to http://your_redmine_site/redmine/projects/bug/issues  (Issue List page)
  (You can go to this page with clicking “issues” (maybe “Tarefa”).
2. Then you can find the link such as “Lista de models” and “Incluir model” at the right side.
   (Sidebar)

3. Click  “Lista de models” and you can see the template lists.
4. Click  “Incluir model” and you can create new template.

The error from project setting screen may be a bug and I’ll fix it soon.  So that please enter the template’s list screen from project’s “issues” tab.

**Comment by akiko-pusu** [comment]
Ok, I’ve just fixed these defect and update README. (commit 29af738cff1fa8)
Also I applied template when creating GitHub issue with ISSUE_TEMPLATE.md.

Master branch has already fixed this bug. 
Please update (git clone or git pull) to apply the bugfix version.

**Comment by vividtone** [comment]
@carodrigues I recommend you to uninstall all plugins except redmine_issue_templates and test if the problem is reproducible.

If the plugin works fine after uninstalling other plugins, it is not the problem of the plugin and the author has nothing to do with it. Only you can do is to uninstall conflicting plugins.

**Comment by akiko-pusu** [comment]
@vividtone  Thank you for the timely help and advice to @carodrigues.
It seems you run Redmine in development mode on your localhost.
I personally think it's not difficult for you to remove and restore any other plugins, so that you should better to evaluate plugins one by one, to avoide conflict with other plugins.
