### ISSUE TITLE
Global note templates

### ISSUE THREAD

**Issue by yaegashi** [akiko-pusu/redmine_issue_templates#268]
Hi, thanks for the great plugin.

I've noticed that there's no global note templates yet.  It would be very useful when we want to share the same templates among unrelated projects. Do you have any plan to have this feature in the roadmap?

**Comment by akiko-pusu** [comment]
Hi, @yaegashi 
Thanks for your feedback!
I released this note template as a prototype because I wonder this feature is useful or not.
So any comments or requests are welcomed.
I think global note template feature is reasonable and want to implement.

If someone who is looking at this issue and it's nice, please vote :-)

**Comment by lamhaison** [comment]
Me too. I really  want that feature because In my case, every alert in my system needs have a report(report like a template note includes now status, reason, solution). I want use this template for all my projects. But at the moment, I have to create it for each project(duplicate settings). Then I vote for that helpful feature.

**Comment by akiko-pusu** [comment]
Implemented on v1.0.2.
Feedback highly appreciate!
