### ISSUE TITLE
Non-admin users cannot select most issue fields when configuring an issue template

### ISSUE THREAD

**Issue by vividtone** [akiko-pusu/redmine_issue_templates#309]
Congratulations on the release of version 1.0. I pay tribute to your effort for years.

## Summary

Non-admin users cannot select most issue fields when configuring an issue template. The only fields they can select are Status and Priority. Of course, the user is allowed to edit other fields. All fields are shown if the current user has admin privilege.

## Environment

- Redmine version: trunk (r19461)
- Ruby version: 2.6.5
- OS Platform: macOS 10.14.6
- Database (MariaDB, MySQL, PostgreSQL) and its version: SQLite3
- Rails Env: development

## Visual Proof / Screenshot

<img width="521" alt="image" src="https://user-images.githubusercontent.com/114863/73131278-88cbbd80-404b-11ea-8084-a2a0039405ed.png">

**Comment by akiko-pusu** [comment]
Thanks for your trying and reporting!

> The only fields they can select are Status and Priority.

Let me confirm the situation. 

**1. Select a tracker?**

When creating an issue template and **if tracker is not selected yet**, "Select a field" pulldown only has two such as Status and Priority.

**2. Ajax request is sent?**

After selecting tracker, ajax get request is sent and selectable fields are shown. (Update select options via ajax)

```
# like this
Started GET "/issue_templates/load_selectable_fields?tracker_id=4&template_id=" for ::1 at 2020-01-26 16:35:07 +0900
Processing by IssueTemplatesController#load_selectable_fields as */*
  Parameters: {"tracker_id"=>"4", "template_id"=>""}
```

**3. Is there any error message in JavaScript console?**
**4. Is there any error message in Rails log?**

---

If basic feature works fine in case administrator, the problem is due to the user's privileges. 

As you pointed out, I was worried the thing related to the user's privileges.

So first I planned to allow **only administrators** to configure core/custom fields.
Dou you have any useful, practical plans?

Exp. 
A.  Administrators only.
B. At the template setting, a user can update the same fields that the user can deal with when creating a new issue. 
C. At the template setting, a user can update all the fields without admin privileges.

**Comment by akiko-pusu** [comment]
Of course, this is a very experimental feature. 
I'm not sure if this is the right solution to handle the fields in the issue template.

Other good implementations are welcome!

**Comment by vividtone** [comment]
It seems that I have not selected any tracker. Now I can see all fields. Sorry for bothering you.

**Comment by akiko-pusu** [comment]
Thanks!
I think the UI should be more friendly!
