### ISSUE TITLE
0.1.4 not working

### ISSUE THREAD

**Issue by faxe78** [akiko-pusu/redmine_issue_templates#83]
Hi,

Throws an error if go to project settings. 

<img width="811" alt="screenshot 2017-03-01 15 32 10" src="https://cloud.githubusercontent.com/assets/1047366/23464165/4b5fecec-fe94-11e6-8756-e0af62c4fd6a.png">

0.1.3 works fine. 

which additional information can i provide to fix the issue?

system is centos 7.3 with ruby 2.0.

**Comment by akiko-pusu** [comment]
Hi, @faxe78 
Thank you for your issue reporting. This is a quite useful information to whom using this plugin under various Redmine environment.

Difference between v0.1.3 to v0.1.4 is following:
https://github.com/akiko-pusu/redmine_issue_templates/compare/0.1.3...0.1.4

In ruby 2.0, keyword argument without default value is not allowed.
This feature was implemented from ruby2.1, so that I think this error is caused.

Ref: 
https://github.com/akiko-pusu/redmine_issue_templates/blob/50109a582168fcfb1cb473b3ab1b7f2ceb8448d6/app/models/issue_template_setting.rb#L6

Here is a workaround:

```
  class << self
    def apply_template_to_child_projects(project_id: nil)
      return if project_id.blank?
      setting = IssueTemplateSetting.find(project_id)
      setting.apply_template_to_child_projects
    end

    def unapply_template_from_child_projects(project_id: nil)
      return if project_id.blank?
      setting = IssueTemplateSetting.find(project_id)
      setting.unapply_template_from_child_projects
    end
  end
```

Could you tell me if above workaround is effective or not?

BTW, Ruby 2.0.0 has reached EOL on Feb. 24th, 2016 and now I’m testing with using ruby2.2, 2.3.
Do you have some plan to update ruby and Redmine version near future?

**Comment by faxe78** [comment]
Hi,

Thx a lot works. 

I used the ruby version shipped with Centos and as Redhat provides still security updates, i was lazy and did not use a newer version. 

i will do an upgrade to 2.2 or 2.3 later.

Thx

Markus

**Comment by akiko-pusu** [comment]
@faxe78 I’m glad to hear that! Thank you for your information. This is quite helpful for me. 
Now I’m going to apply above workaround and release fixed version, so there is no need to hurry to upgrade ruby version.

**Comment by akiko-pusu** [comment]
Workaround was applied to master branch. Thank you so much!
