### ISSUE TITLE
Glitch with form - template controls placement

### ISSUE THREAD

**Issue by danaivehr** [akiko-pusu/redmine_issue_templates#96]
Noticed a glitch: 
template controls on New Issue form appears above "tracker" field for a moment, and then jump below "tracker" field

Please see illustrations below.
first moment:
![template-field-moment](https://cloud.githubusercontent.com/assets/1226019/24371796/a5746046-1334-11e7-8464-4ee7a522c9f7.png)

moment after:
![template-field-after](https://cloud.githubusercontent.com/assets/1226019/24371807/ae5ffe86-1334-11e7-9795-6f74a5f42490.png)

**Comment by akiko-pusu** [comment]
Hi, thanks for your feedback!
This defect is because the place where plugin can insert its own html elements is defined by Redmine itself as “view hook”.
So, first html element for issue template can only insert just before “tracker” and after loaded emelent, change the place after tracker pulldown with using jQuery.

But I agree with this behavior is not pretty good UX.
Here is a workaround of this issue. 
Could you please try this patch if you have time to review?
If this workaround is effective, I’ll apply into master branch :)

```
diff --git a/app/views/issue_templates/_issue_select_form.html.erb b/app/views/issue_templates/_issue_select_form.html.erb
index ce054c0..b0d1a29 100644
--- a/app/views/issue_templates/_issue_select_form.html.erb
+++ b/app/views/issue_templates/_issue_select_form.html.erb
@@ -1,6 +1,6 @@
 <% return '' unless @issue.project.module_enabled? :issue_templates %>
 <% return '' unless User.current.allowed_to?(:show_issue_templates, @issue.project)  %>
-<div id="template_area">
+<div id="template_area" style="display: none;">
   <p>
     <label for="issue_template"><%=h l(:issue_template)%></label>
     <select id="issue_template" name="issue_template">
diff --git a/app/views/issue_templates/_template_pulldown.html.erb b/app/views/issue_templates/_template_pulldown.html.erb
index 54d0b46..2a67409 100644
--- a/app/views/issue_templates/_template_pulldown.html.erb
+++ b/app/views/issue_templates/_template_pulldown.html.erb
@@ -1,8 +1,11 @@
-<% if grouped_options.length == 0 %>
-  <script type="text/javascript">
-    $('#template_area').toggle();
-  </script>
-<% end %>
+<script type="text/javascript">
+    var length = $('#issue_template > optgroup > option').length;
+    if (length < 1) {
+        $('#template_area').hide();
+    } else {
+        $('#template_area').show();
+    }
+</script>
 <option value="">---</option>
 <%= grouped_options_for_select(grouped_options, default_template) %>
```
Scenario: 

1. As default, HTML element for issue template is marked "display hidden". 
2. If user open new issue, template element is loaded before “tracker” pulldown but at first is not displayed.
3. Just after loaded issue template, it moved after “tracker” pulldown, then ajax request is called and selectable template options are loaded.
4. If selectable template option exists, element for issue template is displayed.

**Comment by danaivehr** [comment]
Hi!

Just tested your patch - now is much better. Template fields still appear after a moment when page is already loaded, but now it isn't so noticeable since tracker field is not jumping anymore and it's not being interpreted as a glitch.

Thanks a lot!
